"""
Gold Trading Bot — Interactive Installation / Setup Wizard
==========================================================
Menu-driven configurator. Reads & writes the `.env` file used by config.py.
Run once after install:   python setup.py

Sections:
  1) Binance API keys
  2) LLM brain (provider / base_url / key / model)
  3) Telegram bot (token + chat id)  ← with live connection test
  4) Trading parameters (modal, leverage, SL/TP, paper mode)
  5) Lihat konfigurasi saat ini
  6) Simpan & keluar
"""
import os, re

ENV_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env")

# field -> (label, default, secret?)
SCHEMA = {
    "binance": [
        ("BINANCE_API_KEY",    "Binance API Key",    "", True),
        ("BINANCE_API_SECRET", "Binance API Secret", "", True),
    ],
    "llm": [
        ("LLM_PROVIDER",   "LLM Provider (openai/anthropic)", "openai", False),
        ("LLM_BASE_URL",   "LLM Base URL",                    "https://api.openai.com/v1", False),
        ("LLM_API_KEY",    "LLM API Key",                     "", True),
        ("LLM_MODEL",      "LLM Model",                       "gpt-4o", False),
    ],
    "telegram": [
        ("TELEGRAM_BOT_TOKEN", "Telegram Bot Token (dari @BotFather)", "", True),
        ("TELEGRAM_CHAT_ID",   "Telegram Chat ID (cek via @userinfobot)", "", False),
    ],
    "news": [
        ("NEWS_API_KEY", "NewsAPI Key (dari newsapi.org)", "", True),
    ],
    "trading": [
        ("TRADE_USDT",    "Modal per trade (USDT)", "50", False),
        ("LEVERAGE",      "Leverage (x)",           "5",  False),
        ("STOP_LOSS_PCT", "Stop loss (mis. 0.005 = 0.5%)", "0.005", False),
        ("TAKE_PROFIT_PCT","Take profit (mis. 0.015 = 1.5%)", "0.015", False),
        ("PAPER_TRADING", "Paper mode? (True/False)", "True", False),
    ],
}


def load_env() -> dict:
    env = {}
    if os.path.exists(ENV_PATH):
        for line in open(ENV_PATH):
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            env[k.strip()] = v.strip().strip('"').strip("'")
    return env


def save_env(env: dict):
    lines = ["# Gold Trading Bot config — generated by setup.py", ""]
    for section, fields in SCHEMA.items():
        lines.append(f"# --- {section.upper()} ---")
        for key, _, _, _ in fields:
            if key in env and env[key] != "":
                lines.append(f'{key}={env[key]}')
        lines.append("")
    with open(ENV_PATH, "w") as f:
        f.write("\n".join(lines))
    print(f"\n✅ Tersimpan ke {ENV_PATH}\n")


def mask(v: str, secret: bool) -> str:
    if not v:
        return "(belum diset)"
    if secret and len(v) > 8:
        return v[:4] + "•" * 6 + v[-3:]
    return v


def prompt_section(env: dict, section: str):
    print(f"\n=== Setup: {section.upper()} ===")
    for key, label, default, secret in SCHEMA[section]:
        cur = env.get(key, "")
        shown = mask(cur, secret) if cur else (default or "(kosong)")
        val = input(f"  {label}\n   [{shown}] > ").strip()
        if val:
            env[key] = val
        elif key not in env and default:
            env[key] = default
    if section == "telegram":
        test_telegram(env)
    elif section == "news":
        test_news(env)


def test_telegram(env: dict):
    token = env.get("TELEGRAM_BOT_TOKEN", "")
    chat  = env.get("TELEGRAM_CHAT_ID", "")
    if not (token and chat):
        print("  ⚠️  Token / chat id belum lengkap, lewati tes.")
        return
    if input("  Kirim pesan tes ke Telegram sekarang? (y/n) > ").strip().lower() != "y":
        return
    try:
        import requests
        r = requests.post(
            f"https://api.telegram.org/bot{token}/sendMessage",
            json={"chat_id": chat,
                  "text": "✅ *Gold Bot* berhasil terhubung ke Telegram!",
                  "parse_mode": "Markdown"}, timeout=10)
        if r.status_code == 200:
            print("  ✅ Pesan tes terkirim! Cek Telegram kamu.")
        else:
            print(f"  ❌ Gagal ({r.status_code}): {r.text[:160]}")
    except Exception as e:
        print(f"  ❌ Error: {e}")


def test_news(env: dict):
    key = env.get("NEWS_API_KEY", "")
    if not key:
        print("  ⚠️  NewsAPI key belum diset, lewati tes.")
        return
    if input("  Tes ambil berita dari NewsAPI sekarang? (y/n) > ").strip().lower() != "y":
        return
    try:
        import requests
        r = requests.get("https://newsapi.org/v2/everything",
                         params={"q": "gold price", "pageSize": 1,
                                 "language": "en", "apiKey": key}, timeout=10)
        data = r.json()
        if r.status_code == 200 and data.get("status") == "ok":
            n = data.get("totalResults", 0)
            sample = (data.get("articles") or [{}])[0].get("title", "")
            print(f"  ✅ NewsAPI OK! {n} artikel ditemukan. Contoh: {sample[:70]}")
        else:
            print(f"  ❌ Gagal: {data.get('message', r.text[:160])}")
    except Exception as e:
        print(f"  ❌ Error: {e}")


def show_config(env: dict):
    print("\n========= KONFIGURASI SAAT INI =========")
    for section, fields in SCHEMA.items():
        print(f"\n[{section.upper()}]")
        for key, label, default, secret in fields:
            print(f"  {key:18s} = {mask(env.get(key,''), secret)}")
    print("========================================")


MENU = """
╔══════════════════════════════════════╗
║   GOLD TRADING BOT — SETUP WIZARD     ║
╠══════════════════════════════════════╣
║  1) Setup Binance API                 ║
║  2) Setup LLM (otak bot)              ║
║  3) Setup Telegram (bot + chat id)    ║
║  4) Setup NewsAPI (berita pasar)      ║
║  5) Setup parameter trading           ║
║  6) Lihat konfigurasi saat ini        ║
║  7) Simpan & keluar                   ║
╚══════════════════════════════════════╝
Pilih (1-7): """


def main():
    env = load_env()
    sections = {"1": "binance", "2": "llm", "3": "telegram",
                "4": "news", "5": "trading"}
    while True:
        choice = input(MENU).strip()
        if choice in sections:
            prompt_section(env, sections[choice])
        elif choice == "6":
            show_config(env)
        elif choice == "7":
            save_env(env)
            print("Selesai! Jalankan bot dengan:  python main.py\n")
            break
        else:
            print("Pilihan tidak valid.")


if __name__ == "__main__":
    main()
